### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by manolo** [ibaca/rxtodo-gwt#1]
checked out and run `mvn clean package` I got errors related to non existing class Key in elemento

**Comment by ibaca** [comment]
yep, I'm using this project to try out ideas and to confirm a nice API with elemento so it frequently gets out of sync 😩. The web-component branch doesn't get good results, and now I'm trying to add basic tools to use elemental2 CustomEvents easily and "type safely" with elemento, doing it in the widget branch. But yep, hehe it is a pretty good idea to at least maintain the master branch working, it is pretty annoying otherwise, so I think I'm going to reorganize and move to master the best-working option, and using other branches to experiment. 👍
